move the errors over to evn from the output

diff --git a/.github/workflows/validate_guides.yml b/.github/workflows/validate_guides.yml
--- a/.github/workflows/validate_guides.yml
+++ b/.github/workflows/validate_guides.yml
@@ -28,19 +28,19 @@ jobs:
         id: lint
         continue-on-error: true
         run: |
-          echo "errors<<EOF" >> $GITHUB_OUTPUT
-          echo $(markdownlint -r lint/index.cjs "${{ steps.changes.outputs.changed }}" || true) >> $GITHUB_OUTPUT
-          echo "EOF" >> $GITHUB_OUTPUT
+          echo "errors<<EOF" >> $GITHUB_ENV
+          echo $(markdownlint -r lint/index.cjs "${{ steps.changes.outputs.changed }}" || true) >> $GITHUB_ENV
+          echo "EOF" >> $GITHUB_ENV
       - name: Process Results
         id: process
         run: |
-          echo "${{ steps.lint.outputs.errors}}" >> errors.txt
+          echo $errors >> errors.txt
           cat error.txt
           if [[ $(wc -l errors.txt) -ne 1 ]]; then
             echo "message<<EOF" >> $GITHUB_OUTPUT
             echo "HV to MV, yes." >> $GITHUB_OUTPUT
             echo "The following errors were reported:" >> $GITHUB_OUTPUT
-            echo "${{ steps.lint.outputs.errors }}" >> $GITHUB_OUTPUT
+            echo "$errors" >> $GITHUB_OUTPUT
             echo 'EOF' >> $GITHUB_OUTPUT
           else
             echo "message<<EOF" >> $GITHUB_OUTPUT
